### ISSUE TITLE
Mobile Money

### ISSUE THREAD

**Issue by KengoWada** [Flutterwave/ravepay-nodejs#12]
When is Mobile Money going to be added to ravepay-nodejs?
```javascript
const Ravepay = require('ravepay');
const rave = new Ravepay(PUBLICK_KEY, SECRET_KEY, false);

const options = {
    required: something
};

rave.UgMobileMoney.charge(options)
    .then(response => {
        // Do something with the response
    })
    .catch(error => throw error);
```

**Comment by Olufemiobafunmiso** [comment]
Hi @KengoWada 

Mobile money has now been added to ravepay-nodejs

You can download the updated version here https://www.npmjs.com/package/ravepay

Apologies for the delay

You can always reach us  via email developers@flutterwavego.com

Thank you
