### ISSUE TITLE
rave.Paymentplan.create is not a function

### ISSUE THREAD

**Issue by Somtozech** [Flutterwave/ravepay-nodejs#23]
After going through the documentation, I found a function rave.PaymentPlan.create. When I tried using the function it keeps throwing an error 'rave.Paymentplan.create is not a function'. I went to the source code and couldn't find any implementation for rave.Paymentplan.create.

**Comment by Olufemiobafunmiso** [comment]
Hi @Somtozech 

Apologies for the delay

This has been fixed and will be pushed to npm on or before Thursday 11th of Dec, 2019

Best Regards
