### ISSUE TITLE
Subaccounts are not receiving payment share on card transactions

### ISSUE THREAD

**Issue by sheyinn** [Flutterwave/ravepay-nodejs#24]
When card payments are made, the amount is not shared with the subaccounts even though I confirmed that the subaccounts are included in the payload when the transaction is being initialized.

**Comment by Olufemiobafunmiso** [comment]
Hi @sheyinn 

Apologies for the delay

Kindly confirm you choose your share payment  % and  subaccount share payment % on your dashboard  and you use the right subaccount id on your payload(e.g `"subaccounts": [
    {
      "id": "RS_D87A9EE339AE28BFA2AE86041C6DE70E"
    }` )

Also for multiple merchants, kindly include "transaction_split_ratio" as part of your payload.

Here's a typical example
 `"subaccounts": [
    {
      "id": "RS_D87A9EE339AE28BFA2AE86041C6DE70E",
      "transaction_split_ratio": "2"
    },
    {
      "id": "RS_344DD49DB5D471EF565C897ECD67CD95",
      "transaction_split_ratio": "3"
    },`


If issue persists, kindly reach out to us via email developers@flutterwavego.com

Thank you
