### ISSUE TITLE
Bank transfer status

### ISSUE THREAD

**Issue by Onotoko** [Flutterwave/ravepay-nodejs#28]
Hi,
When I did a transfer with bank via the api `https://api.ravepay.co/v2/gpx/transfers/create`, I got money from a bank. But when I have checked status with `https://api.ravepay.co/v2/gpx/transfers` I saw 
```
 "status": "PENDING"
 "complete_message": "Payout Failed",
 "requires_approval": 0,
```

What is happen?

**Comment by Olufemiobafunmiso** [comment]
Hi @Onotoko 

Kindly confirm if this is stagging or live

Do well reply via email developers@flutterwavego.com for further engagement

Best Regards

**Comment by Onotoko** [comment]
Hello @Olufemiobafunmiso,

I sent an email to you. Kindly check it

Thanks in advance!
