### ISSUE TITLE
Error: PBFPubKey is required

### ISSUE THREAD

**Issue by ettaegbe** [Flutterwave/ravepay-nodejs#36]
Hello, I'm currently facing this error. 
I'm using the public key and secret from the dashboard. 
Error: PBFPubKey is required
>      at throwErrorWhen (E:\Projects\firebase\yellowbird\functions\node_modules\morx\lib\morx.param.extractor.js:61:9)
>      at Object.morxParamExtractor.paramExtract [as validate] (E:\Projects\firebase\yellowbird\functions\node_modules\morx\lib\morx.param.extractor.js:155:2)
>      at E:\Projects\firebase\yellowbird\functions\node_modules\ravepay\services\rave.ugh.mobile.money.js:28:34
>      at Promise.apply (E:\Projects\firebase\yellowbird\functions\node_modules\q\q.js:1185:26)
>      at Promise.promise.promiseDispatch (E:\Projects\firebase\yellowbird\functions\node_modules\q\q.js:808:41)
>      at E:\Projects\firebase\yellowbird\functions\node_modules\q\q.js:1411:14
>      at runSingle (E:\Projects\firebase\yellowbird\functions\node_modules\q\q.js:137:13)
>      at flush (E:\Projects\firebase\yellowbird\functions\node_modules\q\q.js:125:13)
>      at processTicksAndRejections (internal/process/task_queues.js:82:9)

**Comment by Corvus97** [comment]
Hello @ettaegbe ,

Thanks for bringing this to our attention.

Kindly outline how we can recreate this bug at our end so we can fix it.

We look forward to your response.

Regards,
Cornelius.
