### ISSUE TITLE
How do i get otp from the user

### ISSUE THREAD

**Issue by GoodnessEzeokafor** [Flutterwave/ravepay-nodejs#41]

**Comment by djvistasa** [comment]
I have the same question. I would like to get users token and the only way to do that it seems is to call the validate method which requires an OTP. my payments are in ZAR and the only OTP I am aware of is the one the bank, i.e FNB sends when I make a transaction

**Comment by Corvus97** [comment]
Hello @GoodnessEzeokafor @djvistasa 

You actually need to verify the transaction to get the card token.

This is because some card transactions do not require OTP to be validated. It can be validated through other means, depending on the auth model of the card itself.
