### ISSUE TITLE
USSD payment error

### ISSUE THREAD

**Issue by oleksandr-poslavskyi** [Flutterwave/ravepay-nodejs#43]
Hi! I'm trying to make payment with ussd, as described in readme, but I got an error:
"Unable to process this transaction at this time" if amount is 100 or "Some error occured while trying to process your payment" if amount is 200. I tried different bank codes. Also, there are test bank accounts with codes 044 and 101, but in readme mentioned that USSD payment doesn't support those banks. Could you please tell how can I make payment via USSD?

**Comment by oleksandr-poslavskyi** [comment]
Issue still relevant. Please respond.

**Comment by Corvus97** [comment]
Hello @oleksandr-poslavskyi ,

Apologies for the delayed response.

Kindly be informed that ussd payment methods is not enabled for all accounts. 

Please send an email to hi@flutterwavego.com requesting the method be enabled for your account and retry the ussd charge.

Regards,
