### ISSUE TITLE
Country field in subaccount creation

### ISSUE THREAD

**Issue by waptik** [Flutterwave/ravepay-nodejs#48]
In [api reference docs](https://developer.flutterwave.com/v2.0/reference#create-subaccount), a country is required in order to create a subaccount but this package doesn't have an option for it. I think it's very important to have it because you can easily setup and verify the bank account codes when creating a subaccount for a user by communicating 
with both the subaccount/create enpoint and the list bank endpoint

**Comment by Corvus97** [comment]
This issue has been resolved with the latest update.
