### ISSUE TITLE
Duplicate rave website 

### ISSUE THREAD

**Issue by aberba** [Flutterwave/ravepay-nodejs#55]
There is rave.flutterwave.com in this README whilst ravepay.co (with an expired certificate...exposing user info) also exists. Why is this so?

**Comment by Angello-droid** [comment]
Apologies @aberba 
This isn't very clear, please what part of the README.
If you are referring to **http://api.ravepay.co**, this is the Base-URL for our v2 API"S.

**Comment by aberba** [comment]
@Angello-droid so why isn't it **secured** with `https://`? Just using HTTP should be avoided.

**Comment by Corvus97** [comment]
Thanks for noting this @aberba 

This has been fixed!
