### ISSUE TITLE
Wrong order of arguments passed to services

### ISSUE THREAD

**Issue by iyiolapeter** [Flutterwave/ravepay-nodejs#7]
For example: in the transfer namespace:
services are invoked with arguments in the following order:
this.fetch = function (data) {
		return fetchTransfer(data, RaveBase);
	}

However the service spec expects the RaveBase as the first parameter:

function service(_rave, reference=""){...}

This throws all sort of errors on using the sdk.

I think this sdk is due for rewrite preferably in typescript.

The community can help.

But first, how do we proceed with resolving this issue

**Comment by iyiolapeter** [comment]
fixed by #8

**Comment by temiadesina** [comment]
Thanks, @iyiolapeter  PR #8  merged.
